spring:
  rediis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: wgl
    password: 123456
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.104.244.32:3306/spring_cloud_sell?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: plkj5270PLKJ
  jpa:
    show-sql: true
server:
  port: 8500
