spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: wgl
    password: 123456
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.104.244.32:3306/spring_cloud_sell?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: plkj5270PLKJ
  jpa:
    show-sql: true
server:
  port: 8500
spring.redis.database=0
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.pool.max-active=100
spring.redis.pool.max-wait=-1
spring.redis.pool.max-idle=8
spring.redis.pool.min-idle=0
spring.redis.timeout=0
