server:
  port: 9000
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: wgl
    password: 123456
zuul:
  ignoredServices: '*'
  routes:
    myProduct:
      path: /myProduct/**
      service-id: product
      sensitiveHeaders: 
     myOrder:
      path: /myOrder/**
      service-id: order
      sensitiveHeaders: 
